//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class show
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public show()
        {
            this.tickets = new HashSet<ticket>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string administration { get; set; }
        public string distribution { get; set; }
        public System.DateTime premiere { get; set; }
        public int nrOfTickets { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> tickets { get; set; }
    }
}
